currency-exchange-service:
  name: currency-exchange-service
  path: /currency-exchange
#  ribbon:
#    listOfServers: http://localhost:8201,http://localhost:8202

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  boot:
    admin:
      url: http://localhost:9090