spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tddiaz/spring-cloud-demo.git
          search-paths: config-properties

server:
  port: 8888